// <auto-generated />
using System;
using AutoCar.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoCar.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702042939_CadastroFonteDado")]
    partial class CadastroFonteDado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoCar.Domain.Entities.CategoriaProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_categoria");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("CodCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodCategoria"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("descricao");

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("flg_ativo");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CodCategoria")
                        .IsUnique()
                        .HasDatabaseName("ix_categoria_produto_cod");

                    b.HasIndex("Descricao")
                        .IsUnique()
                        .HasDatabaseName("ix_categoria_produto_descricao");

                    b.ToTable("categoria_produto", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_cliente");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("CodCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodCliente"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("flg_ativo");

                    b.Property<decimal>("LimiteCredito")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_limite_credito");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("razao_social");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("integer")
                        .HasColumnName("sts_tipo_pessoa");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CodCliente")
                        .IsUnique()
                        .HasDatabaseName("ix_cliente_cod");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("ix_cliente_documento");

                    b.HasIndex("RazaoSocial")
                        .HasDatabaseName("ix_cliente_razao_social");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Compra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_compra");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("CodCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_compra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodCompra"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<Guid>("IdFornecedor")
                        .HasColumnType("uuid")
                        .HasColumnName("id_fornecedor");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NumDocumento")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("num_documento");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacao");

                    b.Property<decimal>("VlrTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_total");

                    b.HasKey("Id");

                    b.HasIndex("CodCompra")
                        .IsUnique()
                        .HasDatabaseName("ix_compra_cod");

                    b.HasIndex("IdFornecedor")
                        .HasDatabaseName("ix_compra_fornecedor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("compra", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.CompraItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_compra_item");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("descricao_produto");

                    b.Property<Guid>("IdCompra")
                        .HasColumnType("uuid")
                        .HasColumnName("id_compra");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_produto");

                    b.Property<int>("Qtd")
                        .HasColumnType("integer")
                        .HasColumnName("qtd");

                    b.Property<decimal>("VlrCustoUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_custo_unitario");

                    b.Property<decimal>("VlrTotalItem")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_total_item");

                    b.HasKey("Id");

                    b.HasIndex("IdCompra")
                        .HasDatabaseName("ix_compra_item_compra");

                    b.HasIndex("IdProduto");

                    b.ToTable("compra_item", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Devolucao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_devolucao");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("CodDevolucao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_devolucao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodDevolucao"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<Guid>("IdPreVenda")
                        .HasColumnType("uuid")
                        .HasColumnName("id_pre_venda");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Motivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("motivo");

                    b.Property<decimal>("VlrTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_total");

                    b.HasKey("Id");

                    b.HasIndex("CodDevolucao")
                        .IsUnique()
                        .HasDatabaseName("ix_devolucao_cod");

                    b.HasIndex("IdPreVenda")
                        .HasDatabaseName("ix_devolucao_pre_venda");

                    b.HasIndex("IdUsuario");

                    b.ToTable("devolucao", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.DevolucaoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_devolucao_item");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("descricao_produto");

                    b.Property<Guid>("IdDevolucao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_devolucao");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_produto");

                    b.Property<int>("Qtd")
                        .HasColumnType("integer")
                        .HasColumnName("qtd");

                    b.Property<decimal>("VlrTotalItem")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_total_item");

                    b.Property<decimal>("VlrUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_unitario");

                    b.HasKey("Id");

                    b.HasIndex("IdDevolucao")
                        .HasDatabaseName("ix_devolucao_item_devolucao");

                    b.HasIndex("IdProduto");

                    b.ToTable("devolucao_item", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.EstoqueProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_estoque_produto");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_produto");

                    b.Property<int>("QtdReservada")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_reservada");

                    b.Property<int>("QtdSaldo")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_saldo");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IdProduto")
                        .IsUnique()
                        .HasDatabaseName("ix_estoque_produto_produto");

                    b.ToTable("estoque_produto", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.FonteDado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_fonte");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("CodFonte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_fonte");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodFonte"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("descricao");

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("flg_ativo");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observacao");

                    b.Property<string>("Sistema")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sistema");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CodFonte")
                        .IsUnique()
                        .HasDatabaseName("ix_fonte_dado_cod");

                    b.HasIndex("Descricao", "Sistema")
                        .IsUnique()
                        .HasDatabaseName("ix_fonte_dado_descricao_sistema");

                    b.ToTable("fonte_dado", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_fornecedor");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("CodFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_fornecedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodFornecedor"));

                    b.Property<string>("Contato")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contato");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("flg_ativo");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("razao_social");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("integer")
                        .HasColumnName("sts_tipo_pessoa");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CodFornecedor")
                        .IsUnique()
                        .HasDatabaseName("ix_fornecedor_cod");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("ix_fornecedor_documento");

                    b.HasIndex("RazaoSocial")
                        .HasDatabaseName("ix_fornecedor_razao_social");

                    b.ToTable("fornecedor", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.GrupoProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_grupo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("CodGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_grupo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodGrupo"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("descricao");

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("flg_ativo");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uuid")
                        .HasColumnName("id_categoria");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CodGrupo")
                        .IsUnique()
                        .HasDatabaseName("ix_grupo_produto_cod");

                    b.HasIndex("IdCategoria", "Descricao")
                        .IsUnique()
                        .HasDatabaseName("ix_grupo_produto_categoria_descricao");

                    b.ToTable("grupo_produto", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.LadoPeca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_lado");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("CodLado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_lado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodLado"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("descricao");

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("flg_ativo");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CodLado")
                        .IsUnique()
                        .HasDatabaseName("ix_lado_peca_cod");

                    b.HasIndex("Descricao")
                        .IsUnique()
                        .HasDatabaseName("ix_lado_peca_descricao");

                    b.ToTable("lado_peca", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Marca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_marca");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("CodMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_marca");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodMarca"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("descricao");

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("flg_ativo");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CodMarca")
                        .IsUnique()
                        .HasDatabaseName("ix_marca_cod");

                    b.HasIndex("Descricao")
                        .IsUnique()
                        .HasDatabaseName("ix_marca_descricao");

                    b.ToTable("marca", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Mecanico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_mecanico");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("CodMecanico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_mecanico");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodMecanico"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("flg_ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CodMecanico")
                        .IsUnique()
                        .HasDatabaseName("ix_mecanico_cod");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_mecanico_nome");

                    b.ToTable("mecanico", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.MovimentoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_movimento_estoque");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int?>("CodDocumentoOrigem")
                        .HasColumnType("integer")
                        .HasColumnName("cod_documento_origem");

                    b.Property<int>("CodMovimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_movimento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodMovimento"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<Guid?>("IdDocumentoOrigem")
                        .HasColumnType("uuid")
                        .HasColumnName("id_documento_origem");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_produto");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacao");

                    b.Property<int>("Origem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("sts_origem");

                    b.Property<int>("Qtd")
                        .HasColumnType("integer")
                        .HasColumnName("qtd");

                    b.Property<int>("QtdSaldoApos")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_saldo_apos");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("sts_tipo");

                    b.HasKey("Id");

                    b.HasIndex("CodMovimento")
                        .IsUnique()
                        .HasDatabaseName("ix_movimento_estoque_cod");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("ix_movimento_estoque_data");

                    b.HasIndex("IdDocumentoOrigem")
                        .HasDatabaseName("ix_movimento_estoque_documento_origem");

                    b.HasIndex("IdProduto")
                        .HasDatabaseName("ix_movimento_estoque_produto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("movimento_estoque", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_ordem_servico");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("CodOrdemServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_ordem_servico");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodOrdemServico"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("flg_ativo");

                    b.Property<Guid?>("IdCliente")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cliente");

                    b.Property<Guid?>("IdMecanico")
                        .HasColumnType("uuid")
                        .HasColumnName("id_mecanico");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NomeClienteAvulso")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome_cliente_avulso");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacao");

                    b.Property<int?>("QtdKm")
                        .HasColumnType("integer")
                        .HasColumnName("qtd_km");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("sts_situacao");

                    b.Property<string>("VeiculoAno")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("veiculo_ano");

                    b.Property<string>("VeiculoModelo")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("veiculo_modelo");

                    b.Property<string>("VeiculoMontadora")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("veiculo_montadora");

                    b.Property<string>("VeiculoPlaca")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("veiculo_placa");

                    b.Property<decimal>("VlrDesconto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_desconto");

                    b.Property<decimal>("VlrTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_total");

                    b.HasKey("Id");

                    b.HasIndex("CodOrdemServico")
                        .IsUnique()
                        .HasDatabaseName("ix_ordem_servico_cod");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("ix_ordem_servico_data");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_ordem_servico_cliente");

                    b.HasIndex("IdMecanico")
                        .HasDatabaseName("ix_ordem_servico_mecanico");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("Situacao")
                        .HasDatabaseName("ix_ordem_servico_situacao");

                    b.ToTable("ordem_servico", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.OrdemServicoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_ordem_servico_item");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("DescricaoItem")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("descricao_item");

                    b.Property<Guid>("IdOrdemServico")
                        .HasColumnType("uuid")
                        .HasColumnName("id_ordem_servico");

                    b.Property<Guid?>("IdProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_produto");

                    b.Property<Guid?>("IdServico")
                        .HasColumnType("uuid")
                        .HasColumnName("id_servico");

                    b.Property<int>("Qtd")
                        .HasColumnType("integer")
                        .HasColumnName("qtd");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("sts_tipo_item");

                    b.Property<decimal>("VlrDesconto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_desconto");

                    b.Property<decimal>("VlrTotalItem")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_total_item");

                    b.Property<decimal>("VlrUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_unitario");

                    b.HasKey("Id");

                    b.HasIndex("IdOrdemServico")
                        .HasDatabaseName("ix_ordem_servico_item_os");

                    b.HasIndex("IdProduto");

                    b.HasIndex("IdServico");

                    b.ToTable("ordem_servico_item", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.PosicaoPeca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_posicao");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("CodPosicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_posicao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodPosicao"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("descricao");

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("flg_ativo");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CodPosicao")
                        .IsUnique()
                        .HasDatabaseName("ix_posicao_peca_cod");

                    b.HasIndex("Descricao")
                        .IsUnique()
                        .HasDatabaseName("ix_posicao_peca_descricao");

                    b.ToTable("posicao_peca", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.PreVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_pre_venda");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("CodPreVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_pre_venda");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodPreVenda"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("flg_ativo");

                    b.Property<Guid?>("IdCliente")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cliente");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<string>("NomeClienteAvulso")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome_cliente_avulso");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observacao");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("sts_situacao");

                    b.Property<string>("VeiculoAno")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("veiculo_ano");

                    b.Property<string>("VeiculoModelo")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("veiculo_modelo");

                    b.Property<string>("VeiculoMontadora")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("veiculo_montadora");

                    b.Property<string>("VeiculoPlaca")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("veiculo_placa");

                    b.Property<decimal>("VlrDesconto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_desconto");

                    b.Property<decimal>("VlrTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_total");

                    b.HasKey("Id");

                    b.HasIndex("CodPreVenda")
                        .IsUnique()
                        .HasDatabaseName("ix_pre_venda_cod");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("ix_pre_venda_data");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("ix_pre_venda_cliente");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("Situacao")
                        .HasDatabaseName("ix_pre_venda_situacao");

                    b.ToTable("pre_venda", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.PreVendaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_pre_venda_item");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("descricao_produto");

                    b.Property<Guid>("IdPreVenda")
                        .HasColumnType("uuid")
                        .HasColumnName("id_pre_venda");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_produto");

                    b.Property<decimal>("Qtd")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("qtd");

                    b.Property<decimal>("VlrDesconto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_desconto");

                    b.Property<decimal>("VlrTotalItem")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_total_item");

                    b.Property<decimal>("VlrUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_unitario");

                    b.HasKey("Id");

                    b.HasIndex("IdPreVenda")
                        .HasDatabaseName("ix_pre_venda_item_pre_venda");

                    b.HasIndex("IdProduto");

                    b.ToTable("pre_venda_item", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_produto");

                    b.Property<string>("ArquivoImagem")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("arquivo_imagem");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<string>("CodBarras")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cod_barras");

                    b.Property<string>("CodFabricante")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cod_fabricante");

                    b.Property<int>("CodProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_produto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodProduto"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("descricao");

                    b.Property<string>("DescricaoComplementar")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("descricao_complementar");

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("flg_ativo");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uuid")
                        .HasColumnName("id_categoria");

                    b.Property<Guid?>("IdFonte")
                        .HasColumnType("uuid")
                        .HasColumnName("id_fonte");

                    b.Property<Guid?>("IdFornecedor")
                        .HasColumnType("uuid")
                        .HasColumnName("id_fornecedor");

                    b.Property<Guid?>("IdGrupo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_grupo");

                    b.Property<Guid?>("IdLado")
                        .HasColumnType("uuid")
                        .HasColumnName("id_lado");

                    b.Property<Guid?>("IdMarca")
                        .HasColumnType("uuid")
                        .HasColumnName("id_marca");

                    b.Property<Guid?>("IdPosicao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_posicao");

                    b.Property<int>("Unidade")
                        .HasColumnType("integer")
                        .HasColumnName("sts_unidade");

                    b.Property<decimal>("VlrCusto")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_custo");

                    b.Property<decimal>("VlrVenda")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_venda");

                    b.HasKey("Id");

                    b.HasIndex("CodBarras")
                        .IsUnique()
                        .HasDatabaseName("ix_produto_cod_barras")
                        .HasFilter("cod_barras IS NOT NULL");

                    b.HasIndex("CodProduto")
                        .IsUnique()
                        .HasDatabaseName("ix_produto_cod");

                    b.HasIndex("Descricao")
                        .HasDatabaseName("ix_produto_descricao");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdFonte");

                    b.HasIndex("IdFornecedor");

                    b.HasIndex("IdGrupo");

                    b.HasIndex("IdLado");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdPosicao");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.ProdutoAplicacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_aplicacao");

                    b.Property<int?>("AnoFim")
                        .HasColumnType("integer")
                        .HasColumnName("ano_fim");

                    b.Property<int?>("AnoInicio")
                        .HasColumnType("integer")
                        .HasColumnName("ano_inicio");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("Combustivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sts_combustivel");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_produto");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("modelo");

                    b.Property<string>("Montadora")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("montadora");

                    b.Property<string>("Motorizacao")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("motorizacao");

                    b.Property<string>("Observacao")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("observacao");

                    b.HasKey("Id");

                    b.HasIndex("IdProduto")
                        .HasDatabaseName("ix_produto_aplicacao_produto");

                    b.HasIndex("Montadora", "Modelo")
                        .HasDatabaseName("ix_produto_aplicacao_veiculo");

                    b.ToTable("produto_aplicacao", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.ProdutoSimilar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_similar");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<string>("CodReferencia")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cod_referencia");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uuid")
                        .HasColumnName("id_produto");

                    b.Property<Guid?>("IdProdutoEquivalente")
                        .HasColumnType("uuid")
                        .HasColumnName("id_produto_equivalente");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("marca");

                    b.Property<string>("Observacao")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("observacao");

                    b.HasKey("Id");

                    b.HasIndex("IdProduto")
                        .HasDatabaseName("ix_produto_similar_produto");

                    b.HasIndex("IdProdutoEquivalente")
                        .HasDatabaseName("ix_produto_similar_equivalente");

                    b.HasIndex("Marca", "CodReferencia")
                        .HasDatabaseName("ix_produto_similar_referencia");

                    b.ToTable("produto_similar", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_servico");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("CodServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_servico");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodServico"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("descricao");

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("flg_ativo");

                    b.Property<decimal>("VlrPadrao")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("vlr_padrao");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CodServico")
                        .IsUnique()
                        .HasDatabaseName("ix_servico_cod");

                    b.HasIndex("Descricao")
                        .IsUnique()
                        .HasDatabaseName("ix_servico_descricao");

                    b.ToTable("servico", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_atualizacao");

                    b.Property<int>("CodUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodUsuario"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_criacao");

                    b.Property<bool>("FlgAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("flg_ativo");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("usuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("sts_perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CodUsuario")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_cod");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_login");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Cliente", b =>
                {
                    b.OwnsOne("AutoCar.Domain.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bairro")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("bairro");

                            b1.Property<string>("Cep")
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("cep");

                            b1.Property<string>("Cidade")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("complemento");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("logradouro");

                            b1.Property<string>("Numero")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("numero");

                            b1.Property<string>("Uf")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("uf");

                            b1.HasKey("ClienteId");

                            b1.ToTable("cliente");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Compra", b =>
                {
                    b.HasOne("AutoCar.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("IdFornecedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoCar.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.CompraItem", b =>
                {
                    b.HasOne("AutoCar.Domain.Entities.Compra", null)
                        .WithMany("Itens")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoCar.Domain.Entities.Produto", null)
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Devolucao", b =>
                {
                    b.HasOne("AutoCar.Domain.Entities.PreVenda", null)
                        .WithMany()
                        .HasForeignKey("IdPreVenda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoCar.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.DevolucaoItem", b =>
                {
                    b.HasOne("AutoCar.Domain.Entities.Devolucao", null)
                        .WithMany("Itens")
                        .HasForeignKey("IdDevolucao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoCar.Domain.Entities.Produto", null)
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.EstoqueProduto", b =>
                {
                    b.HasOne("AutoCar.Domain.Entities.Produto", null)
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Fornecedor", b =>
                {
                    b.OwnsOne("AutoCar.Domain.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("FornecedorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bairro")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("bairro");

                            b1.Property<string>("Cep")
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("cep");

                            b1.Property<string>("Cidade")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("complemento");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("logradouro");

                            b1.Property<string>("Numero")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("numero");

                            b1.Property<string>("Uf")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("uf");

                            b1.HasKey("FornecedorId");

                            b1.ToTable("fornecedor");

                            b1.WithOwner()
                                .HasForeignKey("FornecedorId");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.GrupoProduto", b =>
                {
                    b.HasOne("AutoCar.Domain.Entities.CategoriaProduto", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.MovimentoEstoque", b =>
                {
                    b.HasOne("AutoCar.Domain.Entities.Produto", null)
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoCar.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.OrdemServico", b =>
                {
                    b.HasOne("AutoCar.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoCar.Domain.Entities.Mecanico", null)
                        .WithMany()
                        .HasForeignKey("IdMecanico")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoCar.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.OrdemServicoItem", b =>
                {
                    b.HasOne("AutoCar.Domain.Entities.OrdemServico", null)
                        .WithMany("Itens")
                        .HasForeignKey("IdOrdemServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoCar.Domain.Entities.Produto", null)
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoCar.Domain.Entities.Servico", null)
                        .WithMany()
                        .HasForeignKey("IdServico")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.PreVenda", b =>
                {
                    b.HasOne("AutoCar.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoCar.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.PreVendaItem", b =>
                {
                    b.HasOne("AutoCar.Domain.Entities.PreVenda", null)
                        .WithMany("Itens")
                        .HasForeignKey("IdPreVenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoCar.Domain.Entities.Produto", null)
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Produto", b =>
                {
                    b.HasOne("AutoCar.Domain.Entities.CategoriaProduto", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutoCar.Domain.Entities.FonteDado", "Fonte")
                        .WithMany()
                        .HasForeignKey("IdFonte")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoCar.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("IdFornecedor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoCar.Domain.Entities.GrupoProduto", "Grupo")
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoCar.Domain.Entities.LadoPeca", "Lado")
                        .WithMany()
                        .HasForeignKey("IdLado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoCar.Domain.Entities.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutoCar.Domain.Entities.PosicaoPeca", "Posicao")
                        .WithMany()
                        .HasForeignKey("IdPosicao")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("Fonte");

                    b.Navigation("Fornecedor");

                    b.Navigation("Grupo");

                    b.Navigation("Lado");

                    b.Navigation("Marca");

                    b.Navigation("Posicao");
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.ProdutoAplicacao", b =>
                {
                    b.HasOne("AutoCar.Domain.Entities.Produto", null)
                        .WithMany("Aplicacoes")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.ProdutoSimilar", b =>
                {
                    b.HasOne("AutoCar.Domain.Entities.Produto", null)
                        .WithMany("Similares")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoCar.Domain.Entities.Produto", null)
                        .WithMany()
                        .HasForeignKey("IdProdutoEquivalente")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Compra", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Devolucao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.OrdemServico", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.PreVenda", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("AutoCar.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Aplicacoes");

                    b.Navigation("Similares");
                });
#pragma warning restore 612, 618
        }
    }
}
